### PR TITLE
Hide the confirmation with its own API

### PR DESCRIPTION
**Pull request by martin-g**
I am not sure how your examples do not hit my problem, but they use the minified versions of Bootstrap Confirmation and Bootstrap and it is hard to debug it.

In my simple app clicking on "No" button doesn't close the popover because of the check at https://github.com/twbs/bootstrap/blob/027b7efd792f4fab065bc6e71d8d2573cd13cadb/js/tooltip.js#L160. When opening the popover state `click` becomes `true` and later `that.leave(that)` ignores the request to leave/close the popover.
By using `that.$element.confirmation('hide');` I overcome this problem.

### CODE REVIEW

**Comment by martin-g** [comment]
Here is a JSBin: http://jsbin.com/wulozuquma/edit?html,js,console,output

**Comment by mistic100** [comment]
The demo uses Bootstrap 3.2, and the changes in tooltip.js are from 3.3.5 https://github.com/twbs/bootstrap/commit/4b269037cb42cce7898d57890db40ef0cc3bd5f8#diff-f3e99e0bb007ace7a370f0492b9cb5abR160

ps: commits messages are supposed to be short and comprehensive, yours is too long and divagate too much

**Comment by mistic100** [comment]
can't merge, you forgot line 152

**Comment by martin-g** [comment]
I have used the GitHub inline edit facilities.
I'll create a new PR later today.

**Comment by mistic100** [comment]
you can just push another commit to your master branch, no need to create another PR

**Comment by martin-g** [comment]
OK. I've updated the changes, increased the version and ran `grunt` to re-generate the `min.js` file.
Also simplified the commit message.

**Pull request merged**
