### PR TITLE
allow custom trigger

### PR DESCRIPTION
**Pull request by akrom123**

### CODE REVIEW

**Comment by mistic100** [comment]
I really don't get it, why don't you trigger "click" from your app instead of adding a non-standard handling ?

Did you tested it against all possible config ? I remember that were really complex side effects when using anything else then click

**Comment by akrom123** [comment]
i want use this case http://codepen.io/anon/pen/PbzxWQ, but I want disable popover shows on click

**Comment by akrom123** [comment]
??

**Comment by mistic100** [comment]
Proposition : use the flag used by Confirmation to know if the event should be dispatched or not :

```js
$(function() {
  $('.ppvr-text').on('click', function (e, fromConfirmation){
    if (!fromConfirmation) {
      alert('alert');
    }
  });
  
  $('.ppvr-text').confirmation({
    title: 'some textssdfxsfsd',
    placement: 'bottom'
  });
  
  $('.ppvr').hover(
      function () {
        $('.ppvr-text').confirmation('show');
      },
      function () {
        $('.ppvr-text').confirmation('hide');
      }
    );
});
```

It's much cleaner that your PR

**Pull request closed without merging**
