### PR TITLE
Ported bootstrap-confirmation.js to bootstrap v4

### PR DESCRIPTION
**Pull request by zoltansolya**
Bootstrap v3 and v4 are very different, thus I suggest this change is published as a fork.

Since Bootstrap v4 dropped glyphicons, this port's default uses Google's Material Icons instead. Can be overridden of course, I have tests with Font Awesome.

Please review and let me know what you think.

Zoltan

### CODE REVIEW

**Comment by mistic100** [comment]
I suggested here https://github.com/mistic100/Bootstrap-Confirmation/issues/51#issuecomment-264400173 how to manage the different versions in the same repository, I know other projects that do this way.

Thus needs to update the bower and package files according to the dependencies.

You should keep the main IIFE, there are many people who do not use any application bundler and you will polute their global scope with the first four functions.
**OR let's use ES6 for the source and compile it to ES5 in another file, it's IMHO a better solution than including those helpers methods**

Use space indentation (compliant with .editorconfig file).

If there is no icons in Bootstrap 4, I suggest to not any by default, one dependency less and no surprises.

**Comment by mistic100** [comment]
Awesome work BTW 👍

**Comment by zoltansolya** [comment]
Thanks for the feedback!  ES6: I will definitely look into that, but that will take more time.  In the first shot, I will correct the things you mentioned in a commit and then go further.

**Comment by mistic100** [comment]
I think it's the best choice as BT4 itself is in ES6.

I can do the port, I plan to do it without any task runner.
Bootstrap team industrialized their package.json with a LOT of scripts https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L19

**Comment by tomalakgeretkal** [comment]
Looks good @zoltansolya  - an issue though: when you have popout:true, that doesn't work if what you clicked on is another confirmation button. It works in the original examples though.

**Comment by zoltansolya** [comment]
Will issue a new PR with the suggested changes.

**Comment by mistic100** [comment]
You could just add more commits or force push this branch.

**Comment by zoltansolya** [comment]
That's right.  This was my first ever pull request, I thought it will be 'cleaner' to open a new PR.:]  I normally am using my repo (which is not even in Github).  I will follow the incremental approach in the future.

**Comment by noncom** [comment]
@mistic100 @zoltansolya so, how is it going?

**Pull request closed without merging**
